model_type: 'jtnn-fnl'

smiles_input_file: './examples/LogP_JTVAE/all.txt'
output_directory: '../code/results'
scorer_type: 'ampl_model'
num_epochs: 1

#Selection/Optimization params
optimizer_type: 'geneticoptimizer'
tourn_size: 15
mate_prob: 0.7
mutate_prob: 0.1
mutation_std: 1
max_clones: 1
optima_type: "maxima"
selection_type: "tournament"
elite_perc: 0

initial_pop_size: 50
max_population: 50

#Generative model parameters:
##FNL JTVAE specific
vocab_path: './examples/LogP_JTVAE/all_vocab.txt'
model_path: './FNLGMD/examples/LogP_JTVAE/model.epoch-35' #

#AMPL scorer (singularity)
# container_type: 'singularity'
# ampl_image: '/path/to/singularity_container_name.sif' #Set this value to point to the location of your singularity container.
#target_col_name: 'pIC50' #Change this to match your target
working_directory: './FNLGMD' #This directory is what will be mounted to the container to pass files in and out

#AMPL scorer (Docker) The below variables are here to serve as an example of applying a Docker image instead of singularity
container_type: 'docker'
ampl_image: 'atomsci/atomsci-ampl:latest' #Set this to point to the 
target_col_name: 'logP' #Change this to match your target
#working_directory: '/path/to/workspace' #This directory is what will be mounted to the container to pass files in and out
